version: '3.8'

services:
  # Servicio de la aplicación Spring Boot
  exchange-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exchange-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    # networks:
    #   - app-network

# networks:
#   app-network:
#     driver: bridge